#!/usr/bin/env python3
"""Generate and verify the continuous house/earthworks presentation regression.

The opt-in Bevy fixture stages ordinary component changes: a no-op building
write, footprint growth, a new house plus quantized terrain deltas, and removal.
Camera movement remains within one streaming center, so unrelated scene roots
must retain their identities. Every frame has identity evidence; every twelfth
frame has a real PNG and capture sidecar. This is not a connected NPC test.
"""

import argparse
import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
NAME = "construction-refresh"
LAST = 360
PROBE_EVERY = 12
EVENTS = [(0, "baseline"), (24, "noop"), (72, "growth"),
          (132, "earthworks"), (216, "removal")]


def shot_name(frame):
    phase = next(name for start, name in reversed(EVENTS) if frame >= start)
    return f"{frame:04}-{phase}"


def pose(frame):
    # Deliberately stay inside chunk (-2, 1); the returning camera has exactly
    # the starting pose so asset identity checks cannot confuse normal unloads.
    t = (1 - math.cos(math.tau * frame / LAST)) / 2
    return (-104 + 20 * t, 16.0, 114 + 4 * t), 2.75 + 0.12 * t


def scenario(output):
    shots = []
    for frame in range(LAST + 1):
        focus, yaw = pose(frame)
        checks = ""
        if frame % PROBE_EVERY == 0:
            checks = (" assertions: [loaded_chunks_at_least(count: 49), "
                      "prop_roots_at_least(count: 1), grass_batches_at_least(count: 1), "
                      "settlement_buildings_at_least(count: 1)],")
        shots.append(f'        (name: "{shot_name(frame)}", '
                     f"focus: ({focus[0]:.6f}, {focus[1]:.6f}, {focus[2]:.6f}), "
                     f"yaw: {yaw:.6f}, zoom: 100.0, time_of_day: 0.45,{checks}),")
    return f'''// Generated by capture/construction_refresh.py; retain only the generator.
(
    version: 1, name: "{NAME}", map: "village_lab",
    output_dir: {json.dumps(str(output))},
    resolution: (1280, 720), fixed_delta_seconds: 0.016666667,
    target: scene, show_window: false, warmup_frames: 240,
    readiness: (minimum_frames: 90, maximum_frames: 1800,
                minimum_loaded_chunks: 49, stable_loaded_chunk_frames: 20),
    continuous: true, probe_every: {PROBE_EVERY},
    environment: {{
        "FISTFORCE_NO_SETTINGS_FILE": "1",
        "FISTFORCE_CAPTURE_CONSTRUCTION_REFRESH": "1",
        "FISTFORCE_CAPTURE_CLOUDS": "clear",
    }},
    shots: [
{chr(10).join(shots)}
    ],
)
'''


def verify(directory):
    failures = []
    for frame in range(0, LAST + 1, PROBE_EVERY):
        name = shot_name(frame)
        image = directory / f"{name}.png"
        if not image.is_file() or not image.stat().st_size:
            failures.append(f"missing image: {name}")
        try:
            metadata = json.loads((directory / f"{name}.capture.json").read_text())
            if not metadata["assertions"] or any(not a["passed"] for a in metadata["assertions"]):
                failures.append(f"semantic assertion failed: {name}")
        except (OSError, ValueError, KeyError) as error:
            failures.append(f"unreadable capture {name}: {error}")
    try:
        report = json.loads((directory / "construction-refresh.json").read_text())
        frames = [json.loads(line) for line in (directory / "construction-refresh.jsonl").read_text().splitlines()]
        if not report["passed"]:
            failures.extend(report["issues"])
        if [entry["frame"] for entry in frames] != list(range(LAST + 1)):
            failures.append("identity evidence did not sample every frame exactly once")
        if any(frame["issues"] for frame in frames):
            failures.append("one or more individual frames lost protected scene identities")
        if not all(report[key] for key in ("terrain_replaced", "deltas_ingested", "added_home_ready")):
            failures.append("final replacement or scene readiness was not proven")
    except (OSError, ValueError, KeyError) as error:
        failures.append(f"unreadable identity evidence: {error}")
    if failures:
        raise SystemExit("Construction refresh verification failed:\n- " + "\n- ".join(failures))
    print("361 continuous identity samples and 31 real probes passed. Inspect PNGs around each change.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=REPO / "logs/construction-refresh/scenario")
    parser.add_argument("--captures", type=Path, help="PNG/JSON directory (default OUTPUT/frames)")
    parser.add_argument("--verify", type=Path, metavar="CAPTURES")
    args = parser.parse_args()
    if args.verify:
        verify(args.verify)
        return
    output = args.output.resolve()
    captures = (args.captures or output / "frames").resolve()
    for path in (output, captures):
        if not path.is_relative_to(REPO / "logs"):
            parser.error("generated scenarios and captures must remain under logs/")
    output.mkdir(parents=True, exist_ok=True)
    path = output / f"{NAME}.ron"
    path.write_text(scenario(captures))
    print(path)
    print(f"361 continuous frames; 31 probes; per-frame identity journal. Captures: {captures}")


if __name__ == "__main__":
    main()
