#!/usr/bin/env python3
"""Generate a four-second, fixed-camera crop wind capture (17 PNG/JSON probes).

Run with target/playtest/capture --scenario GENERATED.ron. The actual imported
farm, loaded terrain and crop meshes must be ready before the uninterrupted
241-frame observation begins. Review roots, ears, soil and shadow motion in
successive PNGs; counters alone cannot prove that the wind shader rendered.
"""

import argparse
import json
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    study = json.loads((repo / "capture/fixtures/town-art-direction.json").read_text())
    output = args.output.resolve()
    if not output.is_relative_to(repo / "logs"):
        parser.error("generated RON and capture output must stay under repository logs/")
    shots = []
    for frame in range(241):
        shots.append(
            f'        (name: "wind-{frame:03}", focus: (-75.0, 15.2, 43.7), '
            'yaw: 2.75, zoom: 32.0, time_of_day: 0.45, '
            'assertions: [settlement_buildings_at_least(count: 65), loaded_chunks_at_least(count: 25)]),'
        )
    scenario = f'''// Generated by capture/crop_wind.py; keep under logs/.
(
    version: 1, name: "crop-wind", map: {json.dumps(study["map_id"])},
    output_dir: {json.dumps(str(output / "frames"))},
    resolution: (1600, 1000), fixed_delta_seconds: 0.016666667,
    target: scene, show_window: false, warmup_frames: 240,
    readiness: (minimum_frames: 90, maximum_frames: 1800,
                minimum_loaded_chunks: 25, stable_loaded_chunk_frames: 20),
    continuous: true, probe_every: 15,
    environment: {{
        "FISTFORCE_NO_SETTINGS_FILE": "1",
        "FISTFORCE_CAPTURE_TOWN_SNAPSHOT": "capture/fixtures/town-art-direction.json",
        "FISTFORCE_CAPTURE_FIT_TOWN_DRESSING": "1",
        "FISTFORCE_CAPTURE_CLOUDS": "clear",
    }},
    shots: [
{chr(10).join(shots)}
    ],
)
'''
    output.mkdir(parents=True, exist_ok=True)
    path = output / "crop-wind.ron"
    path.write_text(scenario)
    print(path)


if __name__ == "__main__":
    main()
