#!/usr/bin/env python3
"""Generate the maintained town art yard/crops -> map -> yard streaming flight.

Only this compact generator belongs in Git. Generated RON, probes and reports
stay under logs/. Run the RON with the real Bevy capture binary, then --verify
its output and inspect the initial/final PNGs and the probes through each LOD.
The initial warmup waits for loaded terrain and the town fixture's actual scene,
field, yard and roadside readiness. Continuous shots never pause for loading;
end assertions and three stable chunk-count probes verify the 180-frame return.
"""

import argparse
import json
import math
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
NAME = "town-art-zoom-roundtrip"
PROBE_EVERY = 30
YARD = ((-140.0, 18.8, 52.0), -0.5, 27.0)
CROP = ((-75.0, 15.2, 43.7), 2.75, 32.0)
TOWN = ((-105.0, 16.0, 93.0), 2.75, 140.0)
REGION = ((-80.0, 16.0, 110.0), 2.75, 900.0)
MAP = ((244.0, 16.0, 244.0), 2.75, 2200.0)
# Last tuple is a complete 180-frame steady return, not an added pre-flight sleep.
LEGS = [
    (60, YARD, "yard-hold"),
    (180, CROP, "to-crops"),
    (240, CROP, "crop-hold"),
    (360, TOWN, "to-town"),
    (420, TOWN, "town-hold"),
    (510, REGION, "to-region"),
    (570, REGION, "region-hold"),
    (660, MAP, "to-map"),
    (720, MAP, "map-hold"),
    (840, YARD, "return"),
    (1020, YARD, "recovered"),
]


def pose(frame):
    previous_frame, previous = 0, YARD
    for end, target, phase in LEGS:
        if frame <= end:
            t = (frame - previous_frame) / (end - previous_frame)
            t = t * t * (3.0 - 2.0 * t)
            focus = tuple(a + (b - a) * t for a, b in zip(previous[0], target[0]))
            angle = math.remainder(target[1] - previous[1], math.tau)
            yaw = previous[1] + angle * t
            zoom = previous[2] * (target[2] / previous[2]) ** t
            # Preserve exact common endpoints for recovery comparisons.
            return (target if t == 1.0 else (focus, yaw, zoom)), phase
        previous_frame, previous = end, target
    raise ValueError(f"frame outside maintained flight: {frame}")


def shot_name(frame):
    return f"{frame:04}-{pose(frame)[1]}"


def scenario(output):
    study = json.loads((REPO / "capture/fixtures/town-art-direction.json").read_text())
    shots = []
    for frame in range(LEGS[-1][0] + 1):
        (focus, yaw, zoom), phase = pose(frame)
        assertions = ["settlements_at_least(count: 1)", "settlement_buildings_at_least(count: 65)"]
        if frame <= 60 or frame >= 930:
            assertions += ["loaded_chunks_at_least(count: 25)", "prop_roots_at_least(count: 1)",
                           "visible_tree_roots_at_least(count: 1)", "grass_batches_at_least(count: 1)"]
        elif phase == "map-hold" and frame >= 690:
            assertions += ["prop_roots_at_most(count: 0)", "grass_batches_at_most(count: 0)"]
        # Only probes evaluate assertions during continuous capture. Do not bloat
        # the generated file with assertions on frames which are never sampled.
        checks = f" assertions: [{', '.join(assertions)}]," if frame % PROBE_EVERY == 0 else ""
        shots.append(
            f'        (name: "{shot_name(frame)}", '
            f"focus: ({focus[0]:.6f}, {focus[1]:.6f}, {focus[2]:.6f}), "
            f"yaw: {yaw:.6f}, zoom: {zoom:.6f}, time_of_day: 0.45,{checks}),"
        )
    return f'''// Generated by capture/town_art_zoom.py; keep under logs/, not Git.
(
    version: 1, name: "{NAME}", map: {json.dumps(study["map_id"])},
    output_dir: {json.dumps(str(output))},
    resolution: (1600, 1000), fixed_delta_seconds: 0.016666667,
    target: scene, show_window: false, warmup_frames: 240,
    readiness: (minimum_frames: 90, maximum_frames: 1800,
                minimum_loaded_chunks: 25, stable_loaded_chunk_frames: 20),
    continuous: true, probe_every: {PROBE_EVERY},
    environment: {{
        "FISTFORCE_NO_SETTINGS_FILE": "1",
        "FISTFORCE_CAPTURE_TOWN_SNAPSHOT": "capture/fixtures/town-art-direction.json",
        "FISTFORCE_CAPTURE_FIT_TOWN_DRESSING": "1",
        "FISTFORCE_CAPTURE_CLOUDS": "clear",
    }},
    shots: [
{chr(10).join(shots)}
    ],
)
'''


def verify(directory):
    probes = {}
    failures = []
    for frame in range(0, LEGS[-1][0] + 1, PROBE_EVERY):
        name = shot_name(frame)
        image = directory / f"{name}.png"
        if not image.is_file() or image.stat().st_size == 0:
            failures.append(f"missing image: {name}")
        path = directory / f"{name}.capture.json"
        try:
            probe = json.loads(path.read_text())
            probes[frame] = probe
            if any(not item["passed"] for item in probe["assertions"]):
                failures.append(f"semantic assertion failed: {name}")
        except (OSError, ValueError, KeyError) as error:
            failures.append(f"unreadable evidence {name}: {error}")
    if 60 in probes and 1020 in probes:
        initial, final = probes[60], probes[1020]
        if initial["camera"] != final["camera"]:
            failures.append("final camera differs from initial yard camera")
        for key in ("settlement_buildings", "household_yards", "household_yard_triangles", "farm_fields",
                    "farm_field_triangles", "roadside_batches", "roadside_clusters", "roadside_triangles"):
            before, after = initial["world"].get(key), final["world"].get(key)
            if before is None or before != after or not before:
                failures.append(f"town geometry did not recover {key}: {before} -> {after}")
        chunks = [probes.get(f, {}).get("world", {}).get("loaded_chunks") for f in (960, 990, 1020)]
        if chunks[0] is None or chunks[0] < 25 or len(set(chunks)) != 1:
            failures.append(f"return terrain did not settle across final three probes: {chunks}")
    if failures:
        raise SystemExit("Town zoom verification failed:\n- " + "\n- ".join(failures))
    print(f"{len(probes)} probes passed; town geometry restored and final terrain stable. Inspect PNGs for visual recovery.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", nargs="?", type=Path, default=REPO / "logs/town-art-study/zoom-scenario")
    parser.add_argument("--captures", type=Path, help="PNG/JSON output directory (default OUTPUT/frames)")
    parser.add_argument("--verify", type=Path, metavar="CAPTURES", help="Verify existing capture evidence instead of generating RON")
    args = parser.parse_args()
    if args.verify:
        verify(args.verify)
        return
    output = args.output.resolve()
    captures = (args.captures or output / "frames").resolve()
    for path in (output, captures):
        if not path.is_relative_to(REPO / "logs"):
            parser.error("generated scenarios and captures must stay under the repository logs/ directory")
    output.mkdir(parents=True, exist_ok=True)
    path = output / f"{NAME}.ron"
    path.write_text(scenario(captures))
    print(path)
    print(f"1021 continuous frames; 35 probes; final 180-frame recovery hold. Captures: {captures}")


if __name__ == "__main__":
    main()
