[workspace]
resolver = "2"
members = [
    "shared",
    "server",
    "client",
    "editor",
    "tools/collider_baker",
    "tools/terrain_ktx_builder",
]

[workspace.dependencies]
bevy = { version = "0.18", features = ["vorbis", "jpeg", "ktx2"] }
lightyear = { version = "0.26", features = ["udp", "netcode"] }
serde = { version = "1.0", features = ["derive"] }
bevy_rapier3d = { git = "https://github.com/dimforge/bevy_rapier", rev = "4ab7e7dcc9a5772dcba0defb3625350eff2bd822", package = "bevy_rapier3d" }
noise = "0.9"
rand = "0.8"
ron = "0.8"
image = { version = "0.25", default-features = false, features = ["png"] }

# Faster compile times during development
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
