app = 'fistforce'
primary_region = 'ams'

[build]

# UDP service for game traffic (not HTTP!)
[[services]]
  protocol = "udp"
  internal_port = 5000

  [[services.ports]]
    port = 5000

[env]
  CITYSIM_MAP_ID = "big_world"
  RUST_LOG = "info"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
