//! Durable inter-settlement trade contracts and company route assets.
//!
//! A route belongs to an ordinary company. There is intentionally no special
//! "trade company" category: a quarry concern, bakery or warehouse merchant
//! may all own the same asset and use the same accounting rules.

use bevy::prelude::*;
use serde::{Deserialize, Serialize};

use super::{BuildingId, CompanyId, PersonId, SettlementId, TradeContractId};
use crate::economy::{Good, MarketSeller};

pub const MAX_TRADE_ROUTE_STOPS: usize = 8;

/// Economic purpose of one durable company route. Contract carriers move
/// cargo already owned by a real buyer; merchant routes risk company cash and
/// use their ordered stop instructions.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum TradeRouteMode {
    #[default]
    ContractCarrier,
    Merchant,
}

impl TradeRouteMode {
    pub const fn label(self) -> &'static str {
        match self {
            Self::ContractCarrier => "Contract delivery",
            Self::Merchant => "Merchant trading",
        }
    }
}

/// One instruction in a repeating caravan timetable. A route carries one
/// good in the first implementation, while every stop independently decides
/// whether that good enters or leaves the wagon and whether coin changes
/// hands.
#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum TradeRouteStopAction {
    /// Load company-owned stock from a Storage Hall in this settlement.
    #[default]
    Load,
    /// Buy from this settlement's public exchange using company cash.
    Buy,
    /// Deposit into a company-owned Storage Hall without making a sale.
    Unload,
    /// Consign cargo to this settlement's public exchange at the route floor.
    Sell,
    /// Locked source instruction generated by a buyer-funded civic contract.
    ContractPickup,
    /// Locked destination instruction generated by a buyer-funded contract.
    ContractDelivery,
}

impl TradeRouteStopAction {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Load => "Load owned stock",
            Self::Buy => "Buy at market",
            Self::Unload => "Unload to storage",
            Self::Sell => "Sell at market",
            Self::ContractPickup => "Collect contract cargo",
            Self::ContractDelivery => "Deliver contract cargo",
        }
    }

    pub const fn is_loading(self) -> bool {
        matches!(self, Self::Load | Self::Buy | Self::ContractPickup)
    }

    pub const fn is_unloading(self) -> bool {
        matches!(self, Self::Unload | Self::Sell | Self::ContractDelivery)
    }

    pub const fn is_locked_contract(self) -> bool {
        matches!(self, Self::ContractPickup | Self::ContractDelivery)
    }
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct TradeRouteStop {
    pub settlement: SettlementId,
    pub action: TradeRouteStopAction,
}

/// Ordered, bounded timetable attached to a route asset. `Vec` keeps the
/// editor straightforward while the authoritative boundary enforces the
/// eight-stop cap; this component updates only when a master edits a route,
/// not every movement tick.
#[derive(Component, Serialize, Deserialize, Clone, Debug, Default, PartialEq, Eq)]
pub struct TradeRouteSchedule {
    stops: Vec<TradeRouteStop>,
}

impl TradeRouteSchedule {
    pub fn new(stops: impl IntoIterator<Item = TradeRouteStop>) -> Option<Self> {
        let stops: Vec<_> = stops.into_iter().collect();
        (stops.len() >= 2 && stops.len() <= MAX_TRADE_ROUTE_STOPS).then_some(Self { stops })
    }

    pub fn stops(&self) -> &[TradeRouteStop] {
        &self.stops
    }

    pub fn replace(&mut self, stops: impl IntoIterator<Item = TradeRouteStop>) -> bool {
        let stops: Vec<_> = stops.into_iter().collect();
        if stops.len() < 2 || stops.len() > MAX_TRADE_ROUTE_STOPS {
            return false;
        }
        self.stops = stops;
        true
    }

    pub fn contract(origin: SettlementId, destination: SettlementId) -> Self {
        Self {
            stops: vec![
                TradeRouteStop {
                    settlement: origin,
                    action: TradeRouteStopAction::ContractPickup,
                },
                TradeRouteStop {
                    settlement: destination,
                    action: TradeRouteStopAction::ContractDelivery,
                },
            ],
        }
    }
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum TradeContractStatus {
    #[default]
    Open,
    Assigned,
    InTransit,
    Fulfilled,
    Cancelled,
}

impl TradeContractStatus {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Open => "Awaiting carrier",
            Self::Assigned => "Carrier assigned",
            Self::InTransit => "Cargo in transit",
            Self::Fulfilled => "Fulfilled",
            Self::Cancelled => "Cancelled",
        }
    }

    pub const fn is_active(self) -> bool {
        matches!(self, Self::Open | Self::Assigned | Self::InTransit)
    }
}

/// A real civic buyer order backed by cash removed from the destination
/// treasury. Source sellers are paid at collection; unused escrow returns to
/// the destination when the contract closes.
#[derive(Component, Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct CivicTradeContract {
    /// Filled once a real seller has enough listed stock to accept the order.
    /// `None` is a public, cash-backed tender visible to potential suppliers.
    pub origin: Option<SettlementId>,
    pub destination: SettlementId,
    pub good: Good,
    pub source_seller: Option<MarketSeller>,
    pub requested_units: u32,
    pub delivered_units: u32,
    pub maximum_unit_price: u64,
    pub delivery_fee_per_bulk: u64,
    pub reserved_cash: u64,
    pub escrow_cash: u64,
    pub spent_on_goods: u64,
    pub spent_on_freight: u64,
    pub created_day: u32,
    pub last_attempt_day: u32,
    pub status: TradeContractStatus,
}

impl CivicTradeContract {
    pub const fn remaining_units(self) -> u32 {
        self.requested_units.saturating_sub(self.delivered_units)
    }
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum TradeRouteStatus {
    #[default]
    WaitingForPorter,
    GoingToOrigin,
    Loading,
    InTransit,
    Returning,
    Idle,
    Mothballed,
}

impl TradeRouteStatus {
    pub const fn label(self) -> &'static str {
        match self {
            Self::WaitingForPorter => "Waiting for porter",
            Self::GoingToOrigin => "Going to first stop",
            Self::Loading => "Loading cargo",
            Self::InTransit => "Travelling to next stop",
            Self::Returning => "Returning to warehouse",
            Self::Idle => "Idle",
            Self::Mothballed => "Mothballed",
        }
    }
}

/// A reusable logistics asset owned by an ordinary company. The first version
/// serves buyer-funded contracts; the price fields deliberately leave the
/// seam needed by later merchant speculation without creating another route
/// type.
#[derive(Component, Serialize, Deserialize, Clone, Copy, Debug, PartialEq, Eq)]
pub struct CompanyTradeRoute {
    pub company: CompanyId,
    pub warehouse: BuildingId,
    pub mode: TradeRouteMode,
    pub origin: SettlementId,
    pub destination: SettlementId,
    pub good: Good,
    pub cargo_target: u32,
    pub maximum_purchase_price: u64,
    pub minimum_destination_price: u64,
    pub automatic: bool,
    /// The appointed Company Master created and reviews this route through
    /// bounded commercial AI. Player-authored timetables and fixed civic
    /// contracts leave it false.
    #[serde(default)]
    pub autonomous_management: bool,
    /// Forecast retained for explanation and later comparison with realised
    /// results. It is not guaranteed income and may be negative after arrival.
    #[serde(default)]
    pub expected_trip_profit: i64,
    /// Confidence in the possibly stale market report used at founding.
    #[serde(default)]
    pub decision_confidence: u8,
    pub active_contract: Option<TradeContractId>,
    pub assigned_caravaner: Option<PersonId>,
    /// Index into `TradeRouteSchedule`; replicated for map/company UI only.
    pub current_stop: u8,
    pub status: TradeRouteStatus,
    pub completed_trips: u32,
    pub lifetime_units: u32,
    pub lifetime_delivery_revenue: u64,
    /// Company cash spent buying merchant cargo. Contract purchases remain
    /// buyer-funded and are retained only in trip audit fields.
    pub lifetime_purchase_cost: u64,
    /// Asking-value of merchant cargo physically consigned at route stops.
    /// This is not revenue until a real market buyer clears the listing.
    pub lifetime_consigned_value: u64,
}

#[derive(Serialize, Deserialize, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct TradeRouteTrip {
    pub departed_day: u32,
    pub completed_day: u32,
    pub units: u32,
    /// Buyer-funded source purchase, retained for route audit rather than
    /// counted as an expense of the carrier company.
    pub source_purchase_cost: u64,
    pub source_market_fees: u64,
    pub delivery_revenue: u64,
    /// Merchant cargo offered to a destination market during this cycle.
    pub consigned_value: u64,
    pub stops_visited: u8,
    pub travel_world_seconds: u32,
}

pub const MAX_TRADE_ROUTE_TRIPS: usize = 32;

#[derive(Component, Serialize, Deserialize, Clone, Debug, Default, PartialEq, Eq)]
pub struct TradeRouteHistory {
    trips: Vec<TradeRouteTrip>,
}

impl TradeRouteHistory {
    pub fn trips(&self) -> &[TradeRouteTrip] {
        &self.trips
    }

    pub fn record(&mut self, trip: TradeRouteTrip) {
        if self.trips.len() == MAX_TRADE_ROUTE_TRIPS {
            self.trips.remove(0);
        }
        self.trips.push(trip);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn timetable_preserves_order_and_enforces_the_editor_bound() {
        let stops = vec![
            TradeRouteStop {
                settlement: SettlementId(1),
                action: TradeRouteStopAction::Buy,
            },
            TradeRouteStop {
                settlement: SettlementId(2),
                action: TradeRouteStopAction::Sell,
            },
            TradeRouteStop {
                settlement: SettlementId(3),
                action: TradeRouteStopAction::Unload,
            },
        ];
        let schedule = TradeRouteSchedule::new(stops.clone()).unwrap();
        assert_eq!(schedule.stops(), stops);
        assert!(TradeRouteSchedule::new(stops[..1].iter().copied()).is_none());
        assert!(
            TradeRouteSchedule::new((0..=MAX_TRADE_ROUTE_STOPS).map(|index| {
                TradeRouteStop {
                    settlement: SettlementId(index as u64),
                    action: TradeRouteStopAction::Buy,
                }
            }))
            .is_none()
        );
    }

    #[test]
    fn public_contract_schedule_is_locked_and_directional() {
        let schedule = TradeRouteSchedule::contract(SettlementId(7), SettlementId(9));
        assert_eq!(schedule.stops().len(), 2);
        assert_eq!(
            schedule.stops()[0],
            TradeRouteStop {
                settlement: SettlementId(7),
                action: TradeRouteStopAction::ContractPickup,
            }
        );
        assert_eq!(
            schedule.stops()[1],
            TradeRouteStop {
                settlement: SettlementId(9),
                action: TradeRouteStopAction::ContractDelivery,
            }
        );
    }
}
