//! Seed-based world generation — the Valheim model.
//!
//! A generated world is not shipped as data; it is shipped as a *recipe*
//! ([`GeneratedWorld`]): a style, a seed and the map size. Everything —
//! coastline, mountains, rivers, beaches, lakes — is a pure function of those
//! three numbers and is rebuilt identically at load time by every binary
//! (client, server, editor) running this exact code.
//!
//! The recipe used to carry a fourth thing: recorded road-flattening strokes,
//! whose smoothed beds depended on grid state at generation time and so could
//! not be recomputed. Roads are gone — they were the last of the city-builder
//! this repo used to be, they painted an 18 m cobblestone stripe across the
//! countryside, and no shipped world had a single stroke in it. With them went
//! the only part of generation that was not a pure function of the seed.
//!
//! That turns a 644MB baked `edits.ron` into a few KB of RON, and it means
//! map size no longer scales file size: an 8km and a 40km world are the
//! same handful of numbers on disk.
//!
//! Height recipe (see Red Blob Games "terrain from noise" + Inigo Quilez
//! domain warping):
//!  - domain-warped fBm with amplitude tail [1, 1/2, 1/3, 1/4, 1/5]
//!  - exponent redistribution (e^3) so terrain has valleys and peaks
//!    instead of uniform bumps
//!  - ridged noise blended in on a mountain mask for ranges
//!  - island: square-bump distance mask sinks the map edge into ocean;
//!    mainland: a warped directional gradient forms one coastline
//!  - beach shelf: heights near sea level are compressed, producing wide
//!    walkable beaches and shallow wading water
//!  - rivers: channels routed by searching for the lowest ground ahead, with
//!    monotonically descending beds incised below their banks, guaranteed to
//!    reach the sea — planned from `raw_height` only, so they are recomputable
//!    from the seed. Where one meets rising ground it cuts a gorge, which is
//!    what puts passes through the mountains.
//!
//! Determinism rules for anything that lives here:
//!  - all randomness must come from [`splitmix64`]/[`rand01`] seeded from
//!    the world seed — never from thread RNG or time
//!  - nothing here may read grid state produced by an *earlier* mutation.
//!    Road strokes used to, which is why the recipe had to store their beds;
//!    with roads gone, every stage reads only `raw_height` and the recipe is
//!    four numbers. Keep it that way.

use bevy::prelude::*;
use noise::{Fbm, MultiFractal, NoiseFn, Perlin};
use serde::{Deserialize, Serialize};

use crate::map::{HeightmapData, MapBounds};
use crate::terrain::VERTEX_SPACING;

pub const SEA_LEVEL: f32 = 0.0;

/// Half-width of a river's flat bed, in metres. The channel carved by
/// generation and the water surface the client lays in it are two different
/// binaries reading this one number; if they ever disagree the water sits in
/// mid-air beside its own riverbed, which is why this is not a private const in
/// each of them.
pub const RIVER_HALF_WIDTH: f32 = 5.0;

/// How far the carve blends from bed to untouched terrain — the bank.
pub const BANK_WIDTH: f32 = 16.0;

/// How far either side of a centreline a river can put water on the ground.
///
/// The client uses it as the reach of the river water level, and prop/grass
/// scattering uses it as the clearance to keep the banks free. Those two must
/// agree: clear less than the water reaches and trees stand in the river; clear
/// more and there is a bald strip either side, which is the road look this
/// whole exercise was undoing. They were the same expression written out twice
/// in two crates, which is a coincidence waiting to stop being one.
pub const RIVER_WATER_REACH: f32 = RIVER_HALF_WIDTH + 4.0;

/// Version of the terrain formula. A generated world is code + seed, so any
/// change to the generation math silently produces a DIFFERENT world from
/// the same recipe — including between binaries built before/after the
/// change (client vs server desync). Bump this whenever generation output
/// changes; the loader logs an error when a recipe was generated by a
/// different version.
pub const WORLDGEN_VERSION: u32 = 6;

// ============================================================================
// The recipe
// ============================================================================

/// Everything needed to rebuild a generated world's terrain from scratch.
/// Stored in `map.ron`; a few KB regardless of map size.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct GeneratedWorld {
    pub style: WorldStyle,
    pub seed: u64,
    /// [`WORLDGEN_VERSION`] of the code that generated this recipe.
    #[serde(default)]
    pub generator_version: u32,
    /// Half the map edge length in metres. Must agree with the map bounds;
    /// stored so the recipe is self-contained and the mismatch is detectable.
    pub half_extent: f32,
}

impl GeneratedWorld {
    /// Rebuild the full terrain grid: noise field → carve rivers → beach
    /// shelf. Deterministic; identical in every binary.
    pub fn build_grid(&self) -> HeightGrid {
        let field = HeightField::new(self.style, self.seed, self.half_extent);
        HeightGrid::build(&field, self.half_extent)
    }

    /// Rebuild the terrain and package it as the runtime sampling grid.
    pub fn build_heightmap(
        &self,
        bounds: MapBounds,
        water_level: Option<f32>,
    ) -> Result<HeightmapData, String> {
        let half_w = bounds.width() * 0.5;
        let half_d = bounds.depth() * 0.5;
        if (half_w - self.half_extent).abs() > 0.5 || (half_d - self.half_extent).abs() > 0.5 {
            return Err(format!(
                "generated world half_extent {} does not match map bounds {}x{}",
                self.half_extent,
                bounds.width(),
                bounds.depth()
            ));
        }
        let grid = self.build_grid();
        Ok(grid.into_heightmap(bounds, water_level))
    }

    /// Biome/resource sampler for this world — cheap to build (noise
    /// tables only), deterministic from the seed.
    pub fn build_biome_field(&self) -> BiomeField {
        BiomeField::new_with_extent(self.seed, self.half_extent)
    }

    /// The river centrelines this world carves, as `(x, bed_height, z)`.
    ///
    /// The same polylines [`build_grid`](Self::build_grid) cuts into the
    /// terrain. The client re-derives them to lay water in those channels
    /// rather than having them shipped, for the same reason the terrain is not
    /// shipped: they are a function of the seed, and a copy is a thing that can
    /// disagree with the ground.
    pub fn build_rivers(&self) -> Vec<Vec<Vec3>> {
        HeightField::new(self.style, self.seed, self.half_extent).rivers
    }
}

// ============================================================================
// Biomes & resources
// ============================================================================

/// Land biome: decides resource availability and look. Availability is a
/// weighting, never exclusive — every biome has some of everything.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorldBiome {
    /// Open grassland: the farmland biome. Lone trees, flowers.
    Meadows,
    /// Dense woodland: the wood biome.
    Forest,
    /// Rocky hills and moors: the stone biome, iron-bearing.
    Highlands,
    /// High peaks: stone everywhere, the richest iron.
    Mountains,
    /// Below the waterline: sea, lake and river bed.
    ///
    /// Not a *land* biome and deliberately not a "shore" one. A shore biome was
    /// considered and rejected: this world's coast runs from cliff to sandbar
    /// to river mouth to bay, and one label spanning all of that would describe
    /// none of them. Ocean is different — everything under the water really
    /// does share a character.
    Ocean,
}

/// Relative resource availability at a point, 0..1 per resource.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct ResourceProfile {
    pub wood: f32,
    pub stone: f32,
    pub iron: f32,
    pub farmland: f32,
}

impl WorldBiome {
    /// Base availability per biome. Iron is further gated by veins — see
    /// [`BiomeField::resources`] — which makes it rare and concentrated.
    pub fn profile(self) -> ResourceProfile {
        match self {
            WorldBiome::Meadows => ResourceProfile {
                wood: 0.25,
                stone: 0.10,
                iron: 0.02,
                farmland: 0.90,
            },
            WorldBiome::Forest => ResourceProfile {
                wood: 0.95,
                stone: 0.20,
                iron: 0.06,
                farmland: 0.30,
            },
            WorldBiome::Highlands => ResourceProfile {
                wood: 0.15,
                stone: 0.85,
                iron: 0.40,
                farmland: 0.10,
            },
            WorldBiome::Mountains => ResourceProfile {
                wood: 0.05,
                stone: 1.00,
                iron: 0.60,
                farmland: 0.0,
            },
            // Nothing is harvested underwater yet. Kept explicit rather than
            // folded into a wildcard so that adding fish, reeds or salt is a
            // change to this line and not a hunt for where the default was.
            WorldBiome::Ocean => ResourceProfile::default(),
        }
    }
}

/// Seeded biome/resource sampler, independent of the height grid so it can
/// be rebuilt cheaply in every binary (the heightmap supplies height and
/// slope at query time). Same seed → same biomes everywhere, forever.
pub struct BiomeField {
    zone: Fbm<Perlin>,
    vein: Fbm<Perlin>,
    half_extent: f32,
    climate_phase: f32,
}

impl std::fmt::Debug for BiomeField {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("BiomeField").finish_non_exhaustive()
    }
}

impl BiomeField {
    /// Half extent defaults to 4096m; prefer [`Self::new_with_extent`] so the
    /// climate bands scale with the actual map.
    pub fn new(seed: u64) -> Self {
        Self::new_with_extent(seed, 4096.0)
    }

    pub fn new_with_extent(seed: u64, half_extent: f32) -> Self {
        let s = |n: u64| splitmix64(seed ^ n) as u32;
        Self {
            // Biome patches a few hundred metres to ~2km across.
            zone: fbm(s(9), 3, 1.0 / 1_100.0),
            // Iron deposits: mid-frequency, thresholded hard in iron_vein().
            vein: fbm(s(10), 2, 1.0 / 150.0),
            half_extent,
            climate_phase: climate_phase(seed),
        }
    }

    /// The land biome at a point. Callers handle water themselves.
    pub fn biome(&self, x: f32, z: f32, height: f32, slope: f32) -> WorldBiome {
        // Underwater first: every other test below is about land, and a seabed
        // that is steep or high-ish would otherwise come back "Highlands".
        if height < SEA_LEVEL {
            return WorldBiome::Ocean;
        }
        if height > 40.0 || (height > 24.0 && slope > 0.55) {
            return WorldBiome::Mountains;
        }
        if slope > 0.62 {
            return WorldBiome::Highlands;
        }
        let zone = self.zone.get([x as f64, z as f64]) as f32;
        if zone > 0.16 {
            WorldBiome::Forest
        } else if zone < -0.28 {
            WorldBiome::Highlands
        } else {
            WorldBiome::Meadows
        }
    }

    /// Iron deposit intensity 0..1: zero almost everywhere, rising steeply
    /// inside sparse vein patches.
    pub fn iron_vein(&self, x: f32, z: f32) -> f32 {
        let v = self.vein.get([x as f64, z as f64]) as f32;
        ((v - 0.28) / 0.50).clamp(0.0, 1.0)
    }

    /// Effective resource availability at a point: the biome's base profile
    /// with iron gated by veins (rare, concentrated), stone scaled by how
    /// rugged the ground actually is (rocky slopes and peaks quarry better
    /// than flat moor), and everything zeroed in the water.
    pub fn resources(&self, x: f32, z: f32, height: f32, slope: f32) -> ResourceProfile {
        if height < SEA_LEVEL + 1.0 {
            return ResourceProfile::default();
        }
        let mut profile = self.biome(x, z, height, slope).profile();
        profile.iron *= 0.10 + 0.90 * self.iron_vein(x, z);
        profile.stone *= 0.55 + 0.45 * (slope / 0.7).min(1.0);
        // Climate is the economic gradient: crops fail in the frozen north
        // and wither in the desert south, wood thins at both extremes — the
        // temperate middle is the breadbasket, and both poles must trade for
        // food. (Pillar 2: what you see is what the simulation enforces; the
        // visuals sample the same fn.)
        let climate =
            climate_at_with_phase(self.climate_phase, x, z, height, self.half_extent);
        profile.farmland *= (1.0 - climate.frost).max(0.0) * (1.0 - climate.snow);
        profile.wood *= 1.0 - climate.snow * 0.45;
        profile.stone = (profile.stone * (1.0 + climate.frost * 0.20)).min(1.0);
        // Desert: the transition band is thirsty-but-farmable savanna; deep
        // desert grows almost nothing and trees give way to scrub.
        profile.farmland *= (1.0 - climate.dry * 0.9).max(0.0);
        profile.wood *= 1.0 - climate.dry * 0.65;
        profile
    }
}

// ============================================================================
// Seeded noise helpers
// ============================================================================

pub fn splitmix64(mut value: u64) -> u64 {
    value = value.wrapping_add(0x9E37_79B9_7F4A_7C15);
    value = (value ^ (value >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    value = (value ^ (value >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    value ^ (value >> 31)
}

pub fn rand01(state: &mut u64) -> f32 {
    *state = splitmix64(*state);
    ((*state >> 40) as f32) / ((1u64 << 24) as f32)
}

// ============================================================================
// Climate: signed latitude bands (snowy NORTH, temperate middle, desert SOUTH)
// ============================================================================
//
// One pure function of (seed, position, height) — the same contract as the
// surface bands: shaders, the far mesh, the minimap, biome resources, and
// future placement queries (`can_farm`) all sample it, so what the player
// sees IS what the simulation enforces. The wgsl mirror in terrain_splat /
// wind_foliage duplicates the math with the seed phase passed as a uniform;
// any constant change here must be mirrored there (EXACT-copy convention).
//
// The hemispheres are deliberately asymmetric (two snowy poles read as
// boring): north (-z, top of the minimap) freezes, south (+z) scorches into
// desert. The fertile middle is structurally the breadbasket between them.

/// Northern latitude (0 = map middle, 1 = north edge) where the snow band
/// begins at sea level.
pub const CLIMATE_SNOW_LAT: f32 = 0.68;
/// Width of the snow blend band in latitude units.
pub const CLIMATE_SNOW_BAND: f32 = 0.10;
/// Frost (pale, cold-desaturated ground) leads the snowline by this much.
pub const CLIMATE_FROST_LEAD: f32 = 0.10;
/// Altitude cools: latitude offset per metre (pushes snow south, desert back).
pub const CLIMATE_ALT_LAT_PER_M: f32 = 0.004;
/// Southern latitude (0 = map middle, 1 = south edge) where desert begins.
pub const CLIMATE_DESERT_LAT: f32 = 0.35;
/// Width of the desert blend band in southern-latitude units.
pub const CLIMATE_DESERT_BAND: f32 = 0.35;

/// Seed-derived phase for the snowline wobble (mirrored to shaders).
pub fn climate_phase(seed: u64) -> f32 {
    let mut state = seed ^ 0xC11A_7E00;
    rand01(&mut state) * std::f32::consts::TAU
}

/// East-west wobble of the snowline so climate bands meander instead of
/// running as ruler lines. Two incommensurate waves, ~1.6km and ~0.5km.
fn climate_lat_wobble(x: f32, phase: f32) -> f32 {
    0.045 * (x * 0.0039 + phase).sin() + 0.022 * (x * 0.0127 + phase * 2.7).sin()
}

/// Climate factors at a world position. All in 0..1:
/// - `snow`: 1 = full snow cover (northern pole)
/// - `frost`: 1 = cold pale ground (leads and includes the snow zone)
/// - `dry`: 1 = full southern desert
pub struct ClimateSample {
    pub snow: f32,
    pub frost: f32,
    pub dry: f32,
}

pub fn climate_at(seed: u64, x: f32, z: f32, height: f32, half_extent: f32) -> ClimateSample {
    let phase = climate_phase(seed);
    climate_at_with_phase(phase, x, z, height, half_extent)
}

/// Split out so per-vertex/per-pixel callers hoist the phase computation.
pub fn climate_at_with_phase(
    phase: f32,
    x: f32,
    z: f32,
    height: f32,
    half_extent: f32,
) -> ClimateSample {
    let half = half_extent.max(1.0);
    let wobble = climate_lat_wobble(x, phase);
    // Signed hemispheres: north (-z) freezes, south (+z) scorches.
    let north_lat = (-z / half + wobble).max(0.0);
    let south_lat = (z / half + wobble).max(0.0);
    // Altitude cools: high ground snows below the nominal snow latitude (and
    // pushes desert back off southern peaks), capped so temperate mountains
    // frost rather than fully whiting out.
    let alt_push = (height.max(0.0) * CLIMATE_ALT_LAT_PER_M).min(0.30);
    let effective_lat = north_lat + alt_push;

    let snow_start = CLIMATE_SNOW_LAT;
    let snow = smoothstep01(
        (effective_lat - snow_start) / CLIMATE_SNOW_BAND,
    );
    let frost = smoothstep01(
        (effective_lat - (snow_start - CLIMATE_FROST_LEAD)) / CLIMATE_SNOW_BAND,
    );
    let dry = smoothstep01(
        (south_lat - alt_push - CLIMATE_DESERT_LAT) / CLIMATE_DESERT_BAND,
    ) * (1.0 - frost);
    ClimateSample { snow, frost, dry }
}

fn smoothstep01(t: f32) -> f32 {
    let t = t.clamp(0.0, 1.0);
    t * t * (3.0 - 2.0 * t)
}

pub fn fbm(seed: u32, octaves: usize, frequency: f64) -> Fbm<Perlin> {
    Fbm::<Perlin>::new(seed)
        .set_octaves(octaves)
        .set_frequency(frequency)
        .set_lacunarity(2.05)
        .set_persistence(0.5)
}

// ============================================================================
// World styles
// ============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WorldStyle {
    /// One large island ringed by ocean and beaches.
    Island,
    /// A mainland with one coastline, rivers, and highlands.
    Mainland,
    /// The showcase world: a mountain range, a great bay with beaches, an
    /// offshore archipelago, inland lakes, and rivers draining the spine to
    /// the sea — cutting gorges through the range on the way.
    Showcase,
}

impl WorldStyle {
    pub fn label(&self) -> &'static str {
        match self {
            WorldStyle::Island => "Island",
            WorldStyle::Mainland => "Mainland",
            WorldStyle::Showcase => "Great Open World",
        }
    }
}

/// One offshore island: center, radius, peak height.
#[derive(Clone, Copy)]
pub struct IslandSeed {
    pub center: Vec2,
    pub radius: f32,
    pub height: f32,
}

/// An inland basin pushed below sea level — renders as a lake against the
/// global water plane.
#[derive(Clone, Copy)]
pub struct LakeSeed {
    pub center: Vec2,
    pub radius: f32,
    pub depth: f32,
}

// ============================================================================
// Height field: pure functions of the seed
// ============================================================================

pub struct HeightField {
    pub style: WorldStyle,
    pub half_extent: f32,
    warp_x: Fbm<Perlin>,
    warp_z: Fbm<Perlin>,
    base: Fbm<Perlin>,
    ridge: Fbm<Perlin>,
    mountain_mask: Fbm<Perlin>,
    coast_wobble: Fbm<Perlin>,
    /// Continent-scale land/ocean split (wavelength ~ the map itself).
    continents: Fbm<Perlin>,
    /// Regional coastline character: most coasts are clean cutoffs, a few
    /// zones get archipelago-style ragged fringes.
    ragged: Fbm<Perlin>,
    /// Mainland: unit direction pointing toward the ocean side.
    pub coast_dir: Vec2,
    pub rivers: Vec<Vec<Vec3>>, // polylines: (x, bed_height, z)
    // --- Showcase-only shaping ---
    /// Direction the mountain spine runs along, and its offset from center.
    pub range_dir: Vec2,
    pub range_offset: f32,
    /// Center of the flat coastal plain where the village sits.
    pub plains_center: Vec2,
    pub islands: Vec<IslandSeed>,
    pub lakes: Vec<LakeSeed>,
}

impl HeightField {
    pub fn new(style: WorldStyle, seed: u64, half_extent: f32) -> Self {
        let s = |n: u64| splitmix64(seed ^ n) as u32;
        let rng = splitmix64(seed ^ 0xC0A5);
        let coast_angle = ((rng >> 32) as f32 / u32::MAX as f32) * std::f32::consts::TAU;
        let mut field = Self {
            style,
            half_extent,
            warp_x: fbm(s(1), 4, 1.0 / 420.0),
            warp_z: fbm(s(2), 4, 1.0 / 420.0),
            base: fbm(s(3), 5, 1.0 / 300.0),
            ridge: fbm(s(4), 4, 1.0 / 180.0),
            mountain_mask: fbm(s(5), 3, 1.0 / 520.0),
            coast_wobble: fbm(s(6), 3, 1.0 / 240.0),
            // Frequency scales with the map so every size gets a handful of
            // landmasses rather than more, smaller ones.
            continents: fbm(s(7), 3, 1.0 / (half_extent as f64 * 0.75)),
            ragged: fbm(s(8), 2, 1.0 / (half_extent as f64 * 0.55)),
            coast_dir: Vec2::new(coast_angle.cos(), coast_angle.sin()),
            rivers: Vec::new(),
            range_dir: Vec2::X,
            range_offset: 0.0,
            plains_center: Vec2::ZERO,
            islands: Vec::new(),
            lakes: Vec::new(),
        };

        if style == WorldStyle::Showcase {
            let mut rng = splitmix64(seed ^ 0x5AFE_C0DE);
            // Mountain spine runs roughly perpendicular to the coast, set
            // back inland so there is room for plains and beaches.
            let range_angle =
                coast_angle + std::f32::consts::FRAC_PI_2 + (rand01(&mut rng) - 0.5) * 0.7;
            field.range_dir = Vec2::new(range_angle.cos(), range_angle.sin());
            field.range_offset = (rand01(&mut rng) - 0.35) * half_extent * 0.5;
            // Village plain: inland of the coast, away from the spine.
            field.plains_center = -field.coast_dir * half_extent * 0.28
                + Vec2::new(-field.coast_dir.y, field.coast_dir.x)
                    * (rand01(&mut rng) - 0.5)
                    * half_extent
                    * 0.5;

            // Archipelago: islands scattered out at sea beyond the coast.
            let island_count = 4 + (rand01(&mut rng) * 4.0) as usize;
            for _ in 0..island_count {
                let out = half_extent * (0.62 + rand01(&mut rng) * 0.34);
                let lateral = (rand01(&mut rng) - 0.5) * half_extent * 1.5;
                let center = field.coast_dir * out
                    + Vec2::new(-field.coast_dir.y, field.coast_dir.x) * lateral;
                field.islands.push(IslandSeed {
                    center,
                    radius: half_extent * (0.05 + rand01(&mut rng) * 0.10),
                    height: 8.0 + rand01(&mut rng) * 26.0,
                });
            }

            // Inland lakes: basins dropped below the water plane.
            let lake_count = 1 + (rand01(&mut rng) * 2.0) as usize;
            for _ in 0..lake_count {
                let angle = rand01(&mut rng) * std::f32::consts::TAU;
                let dist = half_extent * (0.15 + rand01(&mut rng) * 0.35);
                field.lakes.push(LakeSeed {
                    center: -field.coast_dir * half_extent * 0.15
                        + Vec2::new(angle.cos(), angle.sin()) * dist,
                    radius: half_extent * (0.05 + rand01(&mut rng) * 0.06),
                    depth: 5.0 + rand01(&mut rng) * 6.0,
                });
            }
        }

        field.rivers = field.plan_rivers(seed);
        field
    }

    /// Raw (pre-river, pre-shelf) elevation in meters.
    pub fn raw_height(&self, x: f32, z: f32) -> f32 {
        // Domain warp: sample the noise field at an offset driven by more
        // noise — turns blobby fBm into flowing, organic landforms.
        let wx = self.warp_x.get([x as f64, z as f64]) as f32;
        let wz = self.warp_z.get([x as f64, z as f64]) as f32;
        let px = (x + wx * 90.0) as f64;
        let pz = (z + wz * 90.0) as f64;

        // Base rolling terrain, redistributed so mid-heights sink into
        // valleys (Red Blob: pow(e, 3) with a small fudge factor).
        let e = (self.base.get([px, pz]) as f32 * 0.5 + 0.5).clamp(0.0, 1.0);
        let base = (e * 1.2).powf(3.0).min(1.0);

        // Ridged mountains, only where the mountain mask allows.
        let ridge_raw = self.ridge.get([px, pz]) as f32;
        let ridge = (1.0 - ridge_raw.abs()).powi(2);
        let mask = ((self.mountain_mask.get([px, pz]) as f32 + 0.15) * 1.4).clamp(0.0, 1.0);
        let mountains = ridge * mask * mask;

        let height = base * 20.0 + mountains * 30.0;

        if self.style == WorldStyle::Showcase {
            return self.showcase_height(x, z, base, ridge);
        }

        // Shape against the sea.
        let shape = match self.style {
            WorldStyle::Island => {
                // Square-bump distance mask: 1 at center, 0 at the border,
                // with a wobbled radius so the coast isn't a perfect ring.
                let nx = (x / self.half_extent).clamp(-1.0, 1.0);
                let nz = (z / self.half_extent).clamp(-1.0, 1.0);
                let d = 1.0 - (1.0 - nx * nx) * (1.0 - nz * nz);
                let wobble = self.coast_wobble.get([x as f64, z as f64]) as f32 * 0.16;
                1.0 - (d * 1.35 + wobble).clamp(0.0, 1.0)
            }
            // Showcase returns earlier; this arm keeps the match exhaustive.
            WorldStyle::Mainland | WorldStyle::Showcase => {
                // Signed distance to a wobbled coastline across the map.
                let along = (Vec2::new(x, z).dot(self.coast_dir)) / self.half_extent;
                let wobble = self.coast_wobble.get([x as f64, z as f64]) as f32 * 0.35;
                // > 0 inland, < 0 out at sea.
                (0.55 - along + wobble).clamp(0.0, 1.0).powf(0.65)
            }
        };

        // Blend: interiors keep their height, coasts sink below sea level.
        height * shape + (shape - 0.35) * 14.0
    }

    /// The showcase composition: coastal plains, a ridged mountain spine,
    /// a great bay, an offshore archipelago, and inland lake basins.
    fn showcase_height(&self, x: f32, z: f32, base: f32, ridge: f32) -> f32 {
        let p = Vec2::new(x, z);
        let half = self.half_extent;

        // --- Continents: low-frequency noise splits the disc into several
        // landmasses with real oceans and straits between them — a miniature
        // earth rather than one island. The village's home continent is
        // guaranteed by a soft blob around the plains so the showcase
        // content always has land to live on, and a bay is carved out of
        // its coast for the harbour.
        // Coastline character is regional, like a biome: the ragged mask is
        // ~0 along most coasts (small wobble, clean land/water cutoff) and
        // rises toward 1 in a few zones, which get archipelago-style skerry
        // fringes — instead of every coast being island-speckled.
        let ragged = (self.ragged.get([x as f64, z as f64]) as f32 * 1.6 + 0.15).clamp(0.0, 1.0);
        let ragged = ragged * ragged;
        let coast_wobble =
            self.coast_wobble.get([x as f64, z as f64]) as f32 * (0.08 + 0.55 * ragged);
        // Small positive bias: slightly more land than ocean inside the rim.
        let cn = (self.continents.get([x as f64, z as f64]) as f32 * 1.55 + 0.16).clamp(-1.0, 1.0);
        // Soften the gradient near the coastline so shelves stay wide and
        // walkable while interiors still saturate to full inland lift.
        let cn = cn * (0.30 + 0.70 * cn.abs());
        let home = (0.36 - p.distance(self.plains_center) / half) * 3.0;
        let bay_center = self.plains_center + self.coast_dir * (half * 0.30);
        let bay_d = p.distance(bay_center) / (half * 0.16);
        let bay = (-(bay_d * bay_d)).exp() * 0.90;
        let directional = cn.max(home) - bay + coast_wobble;

        // --- World rim: the world is round and ringed by open ocean (the
        // Valheim shape) — the map boundary is always deep water. The rim is
        // a radial coast in the same normalized units as the directional
        // one, so min() composes them and every downstream stage (inland
        // taper, metres-based depth profile, beach shelf, waterline step)
        // applies to the rim beaches exactly as to the bay side. Max wobble
        // is 0.07 < the 0.14 margin at the nearest boundary point, so the
        // edge is water for every seed by construction.
        let r_norm = p.length() / half;
        let rim_wobble = self.coast_wobble.get([x as f64 * 0.35, z as f64 * 0.35]) as f32 * 0.07;
        let rim = 0.86 - r_norm + rim_wobble;
        let landness = directional.min(rim).clamp(-1.0, 1.0);
        // Island (and island-pedestal) influence fades to zero approaching
        // the map boundary: seeds can land near or past it, and the edge of
        // the world must stay open ocean for every seed. Point-wise, so it
        // only needs to cover the last stretch before the boundary — the
        // archipelago ring (r 0.62..0.96) stays alive.
        let g = ((r_norm - 0.90) / 0.07).clamp(0.0, 1.0);
        let rim_guard = 1.0 - g * g * (3.0 - 2.0 * g);

        // --- Mountain spine: ridged noise inside a band along range_dir ---
        let across_range =
            (p.dot(Vec2::new(-self.range_dir.y, self.range_dir.x)) - self.range_offset) / half;
        let spine_wobble = self.mountain_mask.get([x as f64 * 0.6, z as f64 * 0.6]) as f32 * 0.22;
        let band = (-((across_range + spine_wobble) * (across_range + spine_wobble)) / 0.055).exp();
        // Only build mountains on land, and taper them toward the coast.
        // Saturates quickly (×1.6) so the interior gets full-height ranges —
        // the rim coast caps landness at ~0.86, which would otherwise shave
        // every peak in the world, not just the ones near water.
        let inland = (landness.max(0.0) * 1.6).min(1.0).powf(0.6);
        let spine = ridge.powf(1.35) * band * inland;

        // --- Coastal plain around the village: flatten a soft disc ---
        let plain_d = p.distance(self.plains_center) / (half * 0.22);
        let plain_flat = (1.0 - plain_d.clamp(0.0, 1.0)).powf(1.6);

        // Assemble the land surface.
        let rolling = base * 16.0 + (1.0 - band) * base * 10.0;
        let mut height = rolling + spine * 78.0;
        // Flatten toward a gentle 3.5m shelf where the village sits.
        height = height * (1.0 - plain_flat * 0.85) + 3.5 * plain_flat * 0.85;

        // Sink everything seaward of the coastline. Depth is measured in
        // absolute metres offshore rather than as a fraction of map size —
        // the old normalized term (landness * 16) left kilometres of
        // ankle-deep water on an 8km map, which read as a giant pale apron
        // around every coast once the water shades by depth.
        let lift = (landness.max(0.0) * 1.3).min(1.0);
        height = height * lift.powf(0.75) + lift * 16.0;
        if landness < 0.0 {
            let seaward_m = -landness * half;
            // Wade band: a gentle shelf for the first ~60m (beaches,
            // harbours), then the floor drops to open-ocean depth over the
            // next ~250m.
            let wade = (seaward_m / 60.0).min(1.0) * 4.0;
            let drop_t = ((seaward_m - 60.0) / 250.0).clamp(0.0, 1.0);
            let drop = drop_t * drop_t * (3.0 - 2.0 * drop_t) * 30.0;
            // Islands rise from pedestals: keep the floor shallow around
            // each island seed so the archipelago holds its beaches instead
            // of drowning in the new deep water.
            let mut pedestal = 0.0f32;
            for island in &self.islands {
                let d = p.distance(island.center) / island.radius;
                if d < 2.2 {
                    let s = (1.0 - (d / 2.2).clamp(0.0, 1.0)).powf(1.5);
                    pedestal = pedestal.max(s);
                }
            }
            height -= (wade + drop) * (1.0 - pedestal * rim_guard * 0.85);
        }

        // --- Offshore islands: radial bumps rising out of the sea floor ---
        if rim_guard > 0.0 {
            for island in &self.islands {
                let d = p.distance(island.center) / island.radius;
                if d < 1.6 {
                    let falloff = (1.0 - (d / 1.6).clamp(0.0, 1.0)).powf(2.0);
                    // Island tops get their own ridged detail so they aren't domes.
                    let detail = 0.75 + 0.25 * ridge;
                    height += island.height * falloff * detail * rim_guard;
                }
            }
        }

        // --- Inland lake basins: carve below the water plane ---
        for lake in &self.lakes {
            let d = p.distance(lake.center) / lake.radius;
            if d < 1.5 {
                let bowl = (1.0 - (d / 1.5).clamp(0.0, 1.0)).powf(1.5);
                height -= (lake.depth + 4.0) * bowl;
            }
        }

        height
    }

    /// The direction of lowest ground within a forward arc, `probe` metres out.
    ///
    /// Deliberately a **search**, not a gradient. A finite-difference gradient
    /// gives the steepest local descent, which is the direction water
    /// accelerates -- but it is not the direction water *goes*. On a valley
    /// side the steepest descent points at the valley floor, across the
    /// channel, and once you are on the floor it points nowhere useful because
    /// the floor is flat. Following it, a river crabs down one flank and never
    /// settles into the bottom.
    ///
    /// Measured on the shipped world, gradient-following put river 0 in a
    /// valley only 36% of its length and it trenched a median of 14.4 m to get
    /// to the sea. The rivers that did find valleys cut 1.6 m. Sampling the arc
    /// and taking the lowest probe asks the question that actually matters --
    /// "of the places I could be next, which is lowest" -- and a channel found
    /// that way needs almost no carving, because the landscape already had one.
    ///
    /// `seaward` breaks ties toward open water. Terrain built from noise is
    /// full of enclosed hollows, and a pure descent search sits in the first
    /// one it meets forever.
    fn lowest_ahead(&self, at: Vec2, heading: Vec2, probe: f32, seaward: Vec2) -> Vec2 {
        /// Half-angle of the search arc. Wide enough to turn into a side
        /// valley, narrow enough that a river never doubles back uphill.
        const ARC: f32 = 1.15;
        const SAMPLES: usize = 11;
        /// Metres of "height" a fully seaward step is worth in the comparison.
        const SEAWARD_PULL: f32 = 2.2;

        let mut best = heading;
        let mut best_score = f32::MAX;
        for i in 0..SAMPLES {
            let t = (i as f32 / (SAMPLES - 1) as f32) * 2.0 - 1.0;
            let (sin_a, cos_a) = (t * ARC).sin_cos();
            let dir = Vec2::new(
                heading.x * cos_a - heading.y * sin_a,
                heading.x * sin_a + heading.y * cos_a,
            );
            let p = at + dir * probe;
            let score = self.raw_height(p.x, p.y) - dir.dot(seaward) * SEAWARD_PULL;
            if score < best_score {
                best_score = score;
                best = dir;
            }
        }
        best
    }

    /// Plan meandering rivers with monotonically descending beds that end at
    /// the sea (mainland gets 2-3, island gets 0-1 short streams).
    /// Reads only `raw_height`, so rivers are recomputable from the seed.
    ///
    /// # Why these follow the ground
    ///
    /// The first version of this walked a fixed compass bearing with a sine
    /// wiggle on top and dropped its bed a constant 0.28 m per step, never
    /// once reading the terrain it crossed. That produces something with the
    /// wrong silhouette in a specific and recognisable way: real water picks
    /// its way down the lowest ground available, so a channel that ignores the
    /// ground reads as *cut* rather than *found* — which is to say it reads as
    /// a road. It also meant a river was equally likely to trench along a
    /// ridgeline as to run down the valley beside it.
    ///
    /// Now the path steers toward [`Self::downhill`], and the bed is
    /// `min(previous - MIN_FALL, terrain)`. That one expression does both jobs:
    ///
    ///  - where the ground falls faster than `MIN_FALL`, the bed sits ON the
    ///    terrain, so the river lies in the valley it found and the carve is
    ///    shallow — a stream in a dell, not a trench.
    ///  - where the ground rises, the bed keeps descending anyway and the carve
    ///    deepens into a gorge. That is a water gap, the real landform where a
    ///    river cuts through a ridge, and it is what makes a mountain passage.
    ///
    /// So the dramatic gorges are not a special case bolted on; they are what
    /// this rule does when a descending river meets rising ground.
    pub fn plan_rivers(&self, seed: u64) -> Vec<Vec<Vec3>> {
        let mut rng = splitmix64(seed ^ 0x11FE);
        let count = match self.style {
            WorldStyle::Mainland => 2 + (rand01(&mut rng) * 2.0) as usize,
            WorldStyle::Island => (rand01(&mut rng) * 2.0) as usize,
            // Several rivers draining the spine toward the bay.
            WorldStyle::Showcase => 3 + (rand01(&mut rng) * 3.0) as usize,
        };

        let mut rivers = Vec::new();
        // Candidates, not rivers. Routing can fail to find the sea -- a spring
        // behind a ridge, a basin with no outlet -- and those are thrown away
        // below, so roll extra to keep the world's river count roughly what the
        // style asked for.
        for _ in 0..count * 3 {
            if rivers.len() >= count {
                break;
            }
            // Start high inland; flow toward the sea.
            let interior = self.half_extent * 0.45;
            let mut pos = match self.style {
                WorldStyle::Mainland => {
                    // Opposite the coast, offset laterally.
                    let lateral = Vec2::new(-self.coast_dir.y, self.coast_dir.x);
                    -self.coast_dir * interior
                        + lateral * ((rand01(&mut rng) - 0.5) * self.half_extent * 1.2)
                }
                WorldStyle::Island => {
                    let a = rand01(&mut rng) * std::f32::consts::TAU;
                    Vec2::new(a.cos(), a.sin()) * self.half_extent * 0.25
                }
                WorldStyle::Showcase => {
                    // Springs along the mountain spine.
                    let across = Vec2::new(-self.range_dir.y, self.range_dir.x);
                    across * self.range_offset
                        + self.range_dir * ((rand01(&mut rng) - 0.5) * self.half_extent * 1.4)
                }
            };
            // A spring wants high ground: a river that starts halfway down has
            // nothing to cut through and never makes a gorge. Take the highest
            // of a few candidates around the nominal start rather than the
            // first roll, which also stops a spring landing in the sea.
            let mut best = pos;
            let mut best_h = self.raw_height(pos.x, pos.y);
            for _ in 0..6 {
                let a = rand01(&mut rng) * std::f32::consts::TAU;
                let r = rand01(&mut rng) * self.half_extent * 0.18;
                let cand = pos + Vec2::new(a.cos(), a.sin()) * r;
                let h = self.raw_height(cand.x, cand.y);
                if h > best_h {
                    best = cand;
                    best_h = h;
                }
            }
            // A spring needs head. Below this there is not enough fall left to
            // cut a channel, and the river spends kilometres crawling flat at
            // sea level looking for the coast -- which carves a canal, not a
            // river. Measured: a 15 m spring produced 2.2 km of dead-level
            // trench before it found water.
            const MIN_SPRING_HEIGHT: f32 = 22.0;
            if best_h < MIN_SPRING_HEIGHT {
                continue;
            }
            pos = best;

            // Seaward bias. Steepest descent alone strands a river in the first
            // enclosed hollow it meets -- the terrain is noise, so it is full of
            // them. A steady pull toward open water is what "guaranteed to
            // reach the sea" costs, and it is small enough that the downhill
            // term still chooses the route.
            let to_sea = match self.style {
                WorldStyle::Mainland | WorldStyle::Showcase => self.coast_dir,
                WorldStyle::Island => pos.normalize_or(Vec2::X),
            };

            // The spring is incised like every other point. Left at ground
            // level it is the one place on the river where the bed equals the
            // terrain, so the carve there is nothing and the water sits in a
            // slab on open hillside -- a pool with no basin, at the source.
            let mut bed = self.raw_height(pos.x, pos.y) - INCISION;
            let mut points: Vec<Vec3> = vec![Vec3::new(pos.x, bed, pos.y)];
            let meander_seed = rand01(&mut rng) * 100.0;
            let mut dir = to_sea;
            let mut reached_sea = false;
            // Steps spent at sea level without finding the sea.
            let mut flat_steps = 0usize;

            const STEP: f32 = 9.0;
            /// Wide enough to read the valley rather than the noise in it.
            const PROBE: f32 = 42.0;
            /// The gentlest the bed may fall per step. Also the depth the carve
            /// gains per step when it has to cut through rising ground.
            const MIN_FALL: f32 = 0.16;
            /// How far below the surrounding ground the bed always sits.
            ///
            /// Without this the bed tracks the terrain exactly wherever the
            /// ground is already falling — a perfectly reasonable-looking rule
            /// that carves nothing at all there, so the water ends up lying on
            /// open hillside like a ribbon dropped on it. A river is a channel;
            /// it needs banks even where it did not have to cut its way down.
            const INCISION: f32 = 1.4;

            for step in 0..400 {
                let downhill = self.lowest_ahead(pos, dir, PROBE, to_sea);
                let lateral = Vec2::new(-dir.y, dir.x);
                let wiggle = ((step as f32 * 0.09) + meander_seed).sin();
                // Momentum first, or the path corners sharply on every noise
                // bump and reads as a zigzag rather than a river.
                dir = (dir * 0.55 + downhill * 0.95 + lateral * wiggle * 0.18).normalize_or(dir);
                pos += dir * STEP;

                let terrain = self.raw_height(pos.x, pos.y);
                // The rule the whole routine turns on -- see the doc comment.
                // Never below sea level: once a river is down to the waterline
                // it runs flat to the coast as an estuary. Letting it keep
                // descending trenches the sea floor under water nobody can see.
                bed = (bed - MIN_FALL).min(terrain - INCISION).max(SEA_LEVEL);
                points.push(Vec3::new(pos.x, bed, pos.y));

                // An estuary is a few hundred metres of flat water. Past that
                // the river is not approaching a coast, it is tunnelling toward
                // one, and the result reads as a canal cut across the country.
                // Abandon it -- `reached_sea` stays false and it is discarded.
                const MAX_FLAT_STEPS: usize = 32;
                if bed <= SEA_LEVEL {
                    flat_steps += 1;
                    if flat_steps > MAX_FLAT_STEPS {
                        break;
                    }
                } else {
                    flat_steps = 0;
                }

                // Arrival is the GROUND going under, not the bed reaching zero.
                //
                // Those are wildly different places. The bed descends at a
                // fixed rate regardless of terrain, so inland it grinds down to
                // sea level while the ground is still 30 m up -- and stopping
                // there left the river ending in a hollow in the middle of the
                // country. Measured on the shipped world, only one of four
                // rivers finished within 100 m of open water; one stopped
                // 600 m short.
                if terrain < SEA_LEVEL {
                    reached_sea = true;
                    break;
                }
                if pos.x.abs() > self.half_extent * 1.02
                    || pos.y.abs() > self.half_extent * 1.02
                {
                    // Off the edge of the world, which is open ocean.
                    reached_sea = true;
                    break;
                }
            }
            // A river that never found the sea is worse than no river: it is a
            // channel of water lying in open country, connected to nothing.
            if reached_sea && points.len() > 8 {
                rivers.push(points);
            }
        }
        rivers
    }
}

// ============================================================================
// Height grid: the terrain cached on the 2m vertex lattice
// ============================================================================

/// Heights cached on the 2m terrain vertex grid: noise is evaluated once per
/// vertex, rivers are carved directly into the grid, and every consumer
/// (runtime sampling, paint, props, spawn) reads from here. Keeps generation
/// at a few seconds instead of minutes of redundant noise evaluation.
pub struct HeightGrid {
    min: f32,
    spacing: f32,
    size: usize,
    data: Vec<f32>,
}

impl HeightGrid {
    pub fn build(field: &HeightField, half_extent: f32) -> Self {
        let min = -half_extent;
        let spacing = VERTEX_SPACING;
        let size = ((half_extent * 2.0) / spacing) as usize + 1;
        let mut data = vec![0.0f32; size * size];

        for zi in 0..size {
            for xi in 0..size {
                let x = min + xi as f32 * spacing;
                let z = min + zi as f32 * spacing;
                data[zi * size + xi] = field.raw_height(x, z);
            }
        }

        let mut grid = Self {
            min,
            spacing,
            size,
            data,
        };
        grid.carve_rivers(field);
        grid.apply_beach_shelf(field);
        grid
    }

    /// Stamp each river's descending bed into the grid.
    fn carve_rivers(&mut self, field: &HeightField) {
        let influence = RIVER_HALF_WIDTH + BANK_WIDTH;

        for river in &field.rivers {
            for window in river.windows(2) {
                let a = window[0];
                let b = window[1];
                let min_x = a.x.min(b.x) - influence;
                let max_x = a.x.max(b.x) + influence;
                let min_z = a.z.min(b.z) - influence;
                let max_z = a.z.max(b.z) + influence;
                let xi0 = (((min_x - self.min) / self.spacing).floor().max(0.0)) as usize;
                let zi0 = (((min_z - self.min) / self.spacing).floor().max(0.0)) as usize;
                let xi1 = ((((max_x - self.min) / self.spacing).ceil()) as usize).min(self.size - 1);
                let zi1 = ((((max_z - self.min) / self.spacing).ceil()) as usize).min(self.size - 1);

                let pa = Vec2::new(a.x, a.z);
                let seg = Vec2::new(b.x, b.z) - pa;
                let len_sq = seg.length_squared().max(1e-6);

                for zi in zi0..=zi1 {
                    for xi in xi0..=xi1 {
                        let p = Vec2::new(
                            self.min + xi as f32 * self.spacing,
                            self.min + zi as f32 * self.spacing,
                        );
                        let t = ((p - pa).dot(seg) / len_sq).clamp(0.0, 1.0);
                        let dist = p.distance(pa + seg * t);
                        if dist >= influence {
                            continue;
                        }
                        let bed = a.y + (b.y - a.y) * t;
                        let carve = if dist <= RIVER_HALF_WIDTH {
                            1.0
                        } else {
                            let s = (dist - RIVER_HALF_WIDTH) / BANK_WIDTH;
                            1.0 - (s * s * (3.0 - 2.0 * s))
                        };
                        let idx = zi * self.size + xi;
                        let h = self.data[idx];
                        let target = bed + (h - bed) * (1.0 - carve);
                        if target < h {
                            self.data[idx] = target;
                        }
                    }
                }
            }
        }
    }

    /// Compress heights around sea level: wide beaches + shallow shelf.
    ///
    /// The quadratic compression drives the slope to ZERO at the waterline,
    /// which used to leave wide aprons of ground within centimetres of water
    /// height — with the surface animating ±10cm, whole patches flickered
    /// between land and water at close zoom. A small step across the
    /// crossing gives the coast a crisp ~12cm bank instead: ground is always
    /// decisively above the surface, or deeper than any wave crest below it.
    /// The step must stay under the water mesh's shore overlap (0.18m) so
    /// lap waves still have surface to run up the bank.
    fn apply_beach_shelf(&mut self, field: &HeightField) {
        const BAND: f32 = 3.2;
        // Must stay ABOVE the water mesh's 0.18m shore-scan level: foam and
        // shore distance key off the `waterline + 0.18` contour, and a step
        // shorter than that leaves the contour wandering far inland across
        // stepped flats — shorelines there rendered with no white edge at
        // all. 0.22 puts the reference contour exactly on the visible bank.
        const WATERLINE_STEP: f32 = 0.22;

        // The waterline contour wanders at wavelengths finer than the 2m
        // mesh can tessellate, which renders as sawtooth shorelines. Low-pass
        // ONLY the near-waterline strip (3x3 box passes) so the contour
        // itself becomes smooth at mesh scale; everything else keeps its
        // detail. The band is wide enough (±2.4m) that steeper banks still
        // get their crossing cells smoothed — a narrow band skipped them and
        // left raw sawtooth on any coast that rose quickly.
        let mut snapshot = vec![0.0f32; self.data.len()];
        for _ in 0..3 {
            snapshot.copy_from_slice(&self.data);
            for zi in 1..self.size - 1 {
                for xi in 1..self.size - 1 {
                    let idx = zi * self.size + xi;
                    let h = snapshot[idx];
                    if h <= SEA_LEVEL - 2.4 || h >= SEA_LEVEL + 2.4 {
                        continue;
                    }
                    let mut sum = 0.0;
                    for dz in 0..3 {
                        for dx in 0..3 {
                            sum += snapshot[(zi + dz - 1) * self.size + (xi + dx - 1)];
                        }
                    }
                    self.data[idx] = sum / 9.0;
                }
            }
        }

        // On near-perfectly-flat ground the smoothed contour degenerates
        // into long straight runs (the iso-line of an almost-constant field
        // follows the lattice). A gentle ~65m wiggle re-added to the strip
        // curves those coasts naturally; on ordinary slopes a few cm moves
        // the line imperceptibly.
        for zi in 0..self.size {
            for xi in 0..self.size {
                let idx = zi * self.size + xi;
                let h = self.data[idx];
                if h <= SEA_LEVEL - 1.0 || h >= SEA_LEVEL + 1.0 {
                    continue;
                }
                let x = (self.min + xi as f32 * self.spacing) as f64 * 3.7;
                let z = (self.min + zi as f32 * self.spacing) as f64 * 3.7;
                self.data[idx] += field.coast_wobble.get([x, z]) as f32 * 0.06;
            }
        }

        for h in self.data.iter_mut() {
            if *h > SEA_LEVEL - BAND && *h < SEA_LEVEL + BAND {
                let t = (*h - SEA_LEVEL) / BAND;
                *h = SEA_LEVEL
                    + t * t * t.signum() * BAND * 0.55
                    + t.signum() * WATERLINE_STEP;
            }
        }
    }

    pub fn height(&self, x: f32, z: f32) -> f32 {
        let fx = ((x - self.min) / self.spacing).clamp(0.0, (self.size - 1) as f32);
        let fz = ((z - self.min) / self.spacing).clamp(0.0, (self.size - 1) as f32);
        let x0 = fx.floor() as usize;
        let z0 = fz.floor() as usize;
        let x1 = (x0 + 1).min(self.size - 1);
        let z1 = (z0 + 1).min(self.size - 1);
        let tx = fx - x0 as f32;
        let tz = fz - z0 as f32;
        let h00 = self.data[z0 * self.size + x0];
        let h10 = self.data[z0 * self.size + x1];
        let h01 = self.data[z1 * self.size + x0];
        let h11 = self.data[z1 * self.size + x1];
        (h00 * (1.0 - tx) + h10 * tx) * (1.0 - tz) + (h01 * (1.0 - tx) + h11 * tx) * tz
    }

    pub fn slope(&self, x: f32, z: f32) -> f32 {
        let step = self.spacing;
        let dx = (self.height(x + step, z) - self.height(x - step, z)) / (2.0 * step);
        let dz = (self.height(x, z + step) - self.height(x, z - step)) / (2.0 * step);
        (dx * dx + dz * dz).sqrt()
    }

    /// (min, max) over the whole grid — recorded as terrain metadata.
    pub fn height_range(&self) -> (f32, f32) {
        let mut min = f32::MAX;
        let mut max = f32::MIN;
        for &h in &self.data {
            min = min.min(h);
            max = max.max(h);
        }
        (min, max)
    }

    /// Package the grid as the runtime sampling structure. The grid lattice
    /// (min = -half_extent, 2m spacing, size = extent/spacing + 1) maps 1:1
    /// onto [`HeightmapData`]'s bilinear indexing over the same bounds, so
    /// samples are bit-identical between generation and runtime.
    pub fn into_heightmap(self, bounds: MapBounds, water_level: Option<f32>) -> HeightmapData {
        HeightmapData::new(
            bounds,
            self.size as u32,
            self.size as u32,
            self.data,
            water_level,
        )
    }
}

// ============================================================================
// Surface painting
// ============================================================================

/// Surface paint weights (grass, dirt, sand, cobble) from height and slope.
/// The single formula shared by generation-time scatter decisions and runtime
/// weightmap texturing.
///
/// It used to take a third argument, distance to the nearest road, and return
/// an 88%-cobble stripe within 9 m of one. Roads are gone; the cobble layer is
/// now reached only by the steepest faces below, where it reads as bare rock.
pub fn surface_weights_at(h: f32, slope: f32) -> [f32; 4] {
    // Sand: the sea floor and a narrow ribbon at the waterline. Deliberately
    // tight — the coastal lift ramp parks kilometre-wide flats at 1-3m
    // elevation, and a generous band painted them as island-sized beaches.
    // Real beaches end ~a metre above the tide line; low flats are grassland.
    let sand = 1.0 - ((h - (SEA_LEVEL + 0.5)) / 0.7).clamp(0.0, 1.0);
    // Rock (dirt layer): steep faces; cobble on the very steepest.
    let rocky = ((slope - 0.55) / 0.5).clamp(0.0, 1.0);
    let cobble = ((slope - 1.1) / 0.6).clamp(0.0, 1.0);

    let sand = sand * (1.0 - rocky * 0.6);
    let grass = (1.0 - sand - rocky).max(0.0);
    let dirt = (rocky - cobble).max(0.0);
    [grass, dirt, sand, cobble]
}

/// Quantize layer weights to the RGBA bytes the splat shader consumes.
pub fn weights_to_bytes(weights: [f32; 4]) -> [u8; 4] {
    let sum: f32 = weights.iter().map(|w| w.max(0.0)).sum();
    if sum <= f32::EPSILON {
        return [255, 0, 0, 0];
    }
    let mut bytes = [0u8; 4];
    for (byte, weight) in bytes.iter_mut().zip(weights.iter()) {
        *byte = ((weight.max(0.0) / sum) * 255.0).round() as u8;
    }
    // Fix rounding so the sum stays 255 (the shader renormalizes anyway).
    let total: i32 = bytes.iter().map(|b| *b as i32).sum();
    bytes[0] = (bytes[0] as i32 + (255 - total)).clamp(0, 255) as u8;
    bytes
}

/// Shift ground paint toward a biome's character: highlands and mountains
/// read rockier, forests get leaf-litter mottling, meadows stay lush. Only
/// moves weight from grass to the dirt/rock layer — sand and the slope-driven
/// rock stay as computed.
pub fn biome_adjusted_weights(mut weights: [f32; 4], biome: WorldBiome) -> [f32; 4] {
    let shift = match biome {
        WorldBiome::Meadows => 0.0,
        WorldBiome::Forest => 0.12,
        WorldBiome::Highlands => 0.38,
        WorldBiome::Mountains => 0.25,
        // The seabed is painted by height (sand) and slope (rock) like any
        // other ground; shifting grass to dirt underwater would do nothing but
        // muddy the shallows.
        WorldBiome::Ocean => 0.0,
    };
    let moved = weights[0].min(shift);
    weights[0] -= moved;
    weights[1] += moved;
    weights
}

/// Grid-sampling convenience wrapper around [`surface_weights_at`].
pub fn surface_weights(grid: &HeightGrid, x: f32, z: f32, h: f32) -> [f32; 4] {
    surface_weights_at(h, grid.slope(x, z))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A river must arrive at open water, not merely run out of height.
    ///
    /// The distinction is the whole bug this replaced. Routing stopped when the
    /// BED reached sea level, which inland happens hundreds of metres from any
    /// coast -- the bed falls at a fixed rate whatever the ground does. On the
    /// shipped world that left three of four rivers ending in dry country, one
    /// of them 600 m from the nearest open water: a channel full of water,
    /// connected to nothing, starting and stopping in a field.
    ///
    /// So this asserts on reachable sea, not on the mouth's height.
    #[test]
    fn every_river_ends_at_open_water() {
        for seed in [91u64, 7, 2026, 55_555] {
            let field = HeightField::new(WorldStyle::Showcase, seed, 4096.0);
            for (i, r) in field.rivers.iter().enumerate() {
                let mouth = r.last().unwrap();
                if mouth.x.abs() > 4096.0 || mouth.z.abs() > 4096.0 {
                    continue; // ran off the world edge, which is ocean
                }
                let mut distance = f32::MAX;
                'search: for ring in 1..12 {
                    let radius = ring as f32 * 10.0;
                    for k in 0..24 {
                        let a = std::f32::consts::TAU * k as f32 / 24.0;
                        let (px, pz) = (mouth.x + a.cos() * radius, mouth.z + a.sin() * radius);
                        if field.raw_height(px, pz) < SEA_LEVEL - 1.0 {
                            distance = radius;
                            break 'search;
                        }
                    }
                }
                assert!(
                    distance <= 60.0,
                    "seed {seed} river {i} ends at ({:.0},{:.0}), {} m from open sea",
                    mouth.x,
                    mouth.z,
                    if distance == f32::MAX { "120+".into() } else { format!("{distance:.0}") }
                );
            }
        }
    }

    /// Every world must actually get rivers. Candidates are discarded when they
    /// fail to reach the sea, and a filter with no floor under it is one bad
    /// tuning change away from a world with none at all.
    #[test]
    fn every_seed_still_gets_rivers() {
        for seed in [91u64, 7, 2026, 55_555, 12, 900] {
            let field = HeightField::new(WorldStyle::Showcase, seed, 4096.0);
            assert!(
                !field.rivers.is_empty(),
                "seed {seed} produced no rivers at all"
            );
        }
    }

    /// Rivers must stop AT the waterline.
    ///
    /// They used to run until the bed reached -2.5 m, which meant some carried
    /// on out across the sea floor and cut trenches under 30 m of water. That
    /// is invisible terrain detail that costs generation time and shows nobody
    /// anything -- on the shipped world it was two of the four rivers.
    #[test]
    fn rivers_do_not_trench_the_seabed() {
        for seed in [91u64, 7, 2026, 55_555] {
            let field = HeightField::new(WorldStyle::Showcase, seed, 4096.0);
            for (i, r) in field.rivers.iter().enumerate() {
                let submerged = r.iter().filter(|p| p.y < SEA_LEVEL - 0.5).count();
                assert!(
                    submerged <= 1,
                    "seed {seed} river {i} has {submerged} points below sea level; \
                     it is carving the sea floor"
                );
            }
        }
    }

    /// The regression guard for the routing rewrite.
    ///
    /// A river should lie in ground that rises away from it -- that is what a
    /// valley is. When routing followed the height *gradient* instead of
    /// searching for the lowest ground ahead, the worst river on the shipped
    /// world managed this only 36% of its length and had to trench a median of
    /// 14.4 m to reach the sea; the one that did find its valley cut 1.6 m.
    /// Cut depth is the symptom, valley-finding is the cause, so this asserts
    /// on the cause.
    #[test]
    fn rivers_run_along_valleys_not_across_slopes() {
        for seed in [91u64, 7, 2026, 55_555] {
            let field = HeightField::new(WorldStyle::Showcase, seed, 4096.0);
            for (i, r) in field.rivers.iter().enumerate() {
                if r.len() < 12 {
                    continue;
                }
                let mut in_valley = 0;
                let mut total = 0;
                for w in r.windows(2) {
                    let along =
                        Vec2::new(w[1].x - w[0].x, w[1].z - w[0].z).normalize_or(Vec2::X);
                    let side = Vec2::new(-along.y, along.x) * 40.0;
                    let centre = field.raw_height(w[0].x, w[0].z);
                    let left = field.raw_height(w[0].x + side.x, w[0].z + side.y);
                    let right = field.raw_height(w[0].x - side.x, w[0].z - side.y);
                    if 0.5 * (left + right) > centre {
                        in_valley += 1;
                    }
                    total += 1;
                }
                let pct = in_valley * 100 / total;
                assert!(
                    pct >= 55,
                    "seed {seed} river {i} is in a valley only {pct}% of its length \
                     (was 36% with gradient-following; the search fixed it to 86%)"
                );
            }
        }
    }

    /// Different worlds must get different rivers -- the whole point of a
    /// seed. Compares the set of river mouths, which is what a player sees.
    #[test]
    fn rivers_differ_between_seeds() {
        let a = HeightField::new(WorldStyle::Showcase, 91, 4096.0);
        let b = HeightField::new(WorldStyle::Showcase, 92, 4096.0);
        let mouths = |f: &HeightField| -> Vec<(i32, i32)> {
            f.rivers
                .iter()
                .map(|r| {
                    let e = r.last().unwrap();
                    ((e.x / 50.0) as i32, (e.z / 50.0) as i32)
                })
                .collect()
        };
        assert_ne!(
            mouths(&a),
            mouths(&b),
            "two seeds produced rivers ending in the same places"
        );
    }

    /// Numbers behind the river rewrite. `--ignored --nocapture` to read it.
    #[test]
    #[ignore]
    fn river_shape_readout() {
        let half = 4096.0;
        let field = HeightField::new(WorldStyle::Showcase, 91, half);
        println!("{} rivers on the shipped world (Showcase/91)", field.rivers.len());
        for (i, r) in field.rivers.iter().enumerate() {
            let len: f32 = r.windows(2)
                .map(|w| Vec2::new(w[0].x, w[0].z).distance(Vec2::new(w[1].x, w[1].z)))
                .sum();
            let above = r.iter().filter(|p| p.y > SEA_LEVEL).count();
            // How deep the carve is: terrain above the bed at each point.
            let mut cut: Vec<f32> = r
                .iter()
                .map(|p| (field.raw_height(p.x, p.z) - p.y).max(0.0))
                .collect();
            cut.sort_by(|a, b| a.partial_cmp(b).unwrap());
            let median = cut[cut.len() / 2];
            let p90 = cut[cut.len() * 9 / 10];
            let max = *cut.last().unwrap();
            // Is the channel IN a valley? Compare terrain at the centreline
            // with terrain 40 m to either side. Positive = the ground rises
            // away from the river, i.e. it found a valley. Negative = it is
            // running along a slope or a ridge, which is what a road does.
            let mut relief: Vec<f32> = Vec::new();
            for w in r.windows(2) {
                let along = Vec2::new(w[1].x - w[0].x, w[1].z - w[0].z).normalize_or(Vec2::X);
                let side = Vec2::new(-along.y, along.x) * 40.0;
                let c = field.raw_height(w[0].x, w[0].z);
                let l = field.raw_height(w[0].x + side.x, w[0].z + side.y);
                let rr = field.raw_height(w[0].x - side.x, w[0].z - side.y);
                relief.push(0.5 * (l + rr) - c);
            }
            relief.sort_by(|a, b| a.partial_cmp(b).unwrap());
            let in_valley = relief.iter().filter(|v| **v > 0.0).count() * 100 / relief.len();
            println!(
                "  river {i}: {:>4} pts, {:>6.0} m long, bed {:>6.1} -> {:>5.1} m, \
                 {above:>3}/{} above sea | cut median {median:>4.1} p90 {p90:>5.1} max {max:>5.1} m \
                 | in-valley {in_valley:>3}% relief median {:>5.1} m",
                r.len(), len, r[0].y, r.last().unwrap().y, r.len(), relief[relief.len()/2]
            );
            let mid = r[r.len() / 2];
            // How far from the mouth is real open sea? Search outward for
            // terrain the ocean actually covers, ignoring the river's own cut.
            let mouth = r.last().unwrap();
            let mut to_sea = f32::MAX;
            for ring in 1..60 {
                let rad = ring as f32 * 10.0;
                let mut hit = false;
                for k in 0..24 {
                    let a = std::f32::consts::TAU * k as f32 / 24.0;
                    let (px, pz) = (mouth.x + a.cos() * rad, mouth.z + a.sin() * rad);
                    if field.raw_height(px, pz) < SEA_LEVEL - 1.0 {
                        hit = true;
                        break;
                    }
                }
                if hit {
                    to_sea = rad;
                    break;
                }
            }
            println!(
                "            spring ({:.0},{:.0}) h={:.0}  mouth ({:.0},{:.0})  open sea {} m away",
                r[0].x, r[0].z, field.raw_height(r[0].x, r[0].z), mouth.x, mouth.z,
                if to_sea == f32::MAX { "600+".to_string() } else { format!("{to_sea:.0}") }
            );
            let _ = mid;
        }
    }

    fn recipe(half: f32) -> GeneratedWorld {
        GeneratedWorld {
            style: WorldStyle::Showcase,
            seed: 2026,
            generator_version: WORLDGEN_VERSION,
            half_extent: half,
        }
    }

    #[test]
    fn same_seed_builds_identical_terrain() {
        let def = recipe(700.0);
        let a = def.build_grid();
        let b = def.build_grid();
        let mut checked = 0;
        let mut z = -680.0;
        while z < 680.0 {
            let mut x = -680.0;
            while x < 680.0 {
                assert_eq!(a.height(x, z).to_bits(), b.height(x, z).to_bits());
                checked += 1;
                x += 97.0;
            }
            z += 97.0;
        }
        assert!(checked > 100);
    }

    #[test]
    fn different_seed_builds_different_terrain() {
        let a = recipe(700.0).build_grid();
        let b = GeneratedWorld {
            seed: 2027,
            ..recipe(700.0)
        }
        .build_grid();
        let mut differing = 0;
        for i in 0..20 {
            let p = -650.0 + i as f32 * 65.0;
            if a.height(p, -p) != b.height(p, -p) {
                differing += 1;
            }
        }
        assert!(differing > 10);
    }

    #[test]
    fn heightmap_matches_grid_exactly() {
        let def = recipe(512.0);
        let grid = def.build_grid();
        let bounds = MapBounds {
            min: [-512.0, -512.0],
            max: [512.0, 512.0],
        };
        let heightmap = def.build_heightmap(bounds, Some(SEA_LEVEL)).unwrap();
        // On-lattice and off-lattice points must agree: same bilinear basis.
        for (x, z) in [
            (0.0, 0.0),
            (-512.0, -512.0),
            (510.0, 510.0),
            (123.4, -87.9),
            (-3.7, 400.2),
        ] {
            let g = grid.height(x, z);
            let h = heightmap.sample_height(x, z);
            assert!(
                (g - h).abs() < 1e-3,
                "mismatch at ({x},{z}): grid {g} heightmap {h}"
            );
        }
    }

    #[test]
    fn showcase_world_edge_is_always_water() {
        for seed in [7u64, 91, 2026] {
            let half = 700.0;
            let grid = GeneratedWorld {
                style: WorldStyle::Showcase,
                seed,
                generator_version: WORLDGEN_VERSION,
                half_extent: half,
            }
            .build_grid();
            let steps = 80;
            for i in 0..steps {
                let t = -half + (2.0 * half) * (i as f32 / (steps - 1) as f32);
                let inset = half - 2.0;
                for (x, z) in [(t, -inset), (t, inset), (-inset, t), (inset, t)] {
                    let h = grid.height(x, z);
                    assert!(
                        h < SEA_LEVEL,
                        "seed {seed}: land ({h}m) on the world edge at ({x},{z})"
                    );
                }
            }
        }
    }

    #[test]
    fn biomes_are_deterministic_and_iron_is_rare() {
        let a = BiomeField::new(2026);
        let b = BiomeField::new(2026);

        let mut iron_sum = 0.0f32;
        let mut wood_sum = 0.0f32;
        let mut rich_iron_cells = 0u32;
        let mut samples = 0u32;
        let mut biome_counts = [0u32; 5];
        for zi in 0..80 {
            for xi in 0..80 {
                let x = -3900.0 + xi as f32 * 97.0;
                let z = -3900.0 + zi as f32 * 97.0;
                // Flat mid-elevation land: biome comes from the zone noise.
                let (h, slope) = (8.0, 0.1);
                assert_eq!(a.biome(x, z, h, slope), b.biome(x, z, h, slope));

                let r = a.resources(x, z, h, slope);
                iron_sum += r.iron;
                wood_sum += r.wood;
                if r.iron > 0.25 {
                    rich_iron_cells += 1;
                }
                samples += 1;
                biome_counts[match a.biome(x, z, h, slope) {
                    WorldBiome::Meadows => 0,
                    WorldBiome::Forest => 1,
                    WorldBiome::Highlands => 2,
                    WorldBiome::Mountains => 3,
                    WorldBiome::Ocean => 4,
                }] += 1;
            }
        }

        // Iron is rare: far scarcer than wood on average, and rich deposits
        // cover only a small fraction of the world.
        assert!(iron_sum < wood_sum * 0.25, "iron {iron_sum} vs wood {wood_sum}");
        let rich_frac = rich_iron_cells as f32 / samples as f32;
        assert!(
            rich_frac > 0.001 && rich_frac < 0.08,
            "rich iron fraction {rich_frac}"
        );

        // All lowland biomes actually occur.
        assert!(biome_counts[0] > 0, "no meadows");
        assert!(biome_counts[1] > 0, "no forest");
        assert!(biome_counts[2] > 0, "no highlands");

        // Altitude forces mountains regardless of the zone noise.
        assert_eq!(a.biome(0.0, 0.0, 55.0, 0.1), WorldBiome::Mountains);
        // Water yields nothing.
        assert_eq!(a.resources(0.0, 0.0, -3.0, 0.0), ResourceProfile::default());
    }

    /// World probe, not an assertion: lists iron-vein sites for a seed so a
    /// human (or capture run) can go look at them.
    /// `cargo test -p shared probe_vein_sites -- --ignored --nocapture`
    #[test]
    #[ignore = "world probe; run with --ignored --nocapture"]
    fn probe_vein_sites() {
        let def = GeneratedWorld {
            style: WorldStyle::Showcase,
            seed: 91,
            generator_version: WORLDGEN_VERSION,
            half_extent: 4096.0,
        };
        let grid = def.build_grid();
        let biomes = def.build_biome_field();
        let mut found = 0;
        for zi in 0..205 {
            for xi in 0..205 {
                let x = -4080.0 + xi as f32 * 40.0;
                let z = -4080.0 + zi as f32 * 40.0;
                let h = grid.height(x, z);
                if h < 2.0 {
                    continue;
                }
                let s = grid.slope(x, z);
                let vein = biomes.iron_vein(x, z);
                let biome = biomes.biome(x, z, h, s);
                if vein > 0.6
                    && matches!(biome, WorldBiome::Highlands | WorldBiome::Mountains)
                {
                    println!("vein at ({x:.0},{z:.0}) h={h:.1} {biome:?} strength {vein:.2}");
                    found += 1;
                    if found >= 15 {
                        return;
                    }
                }
            }
        }
        println!("{found} vein sites listed");
    }

    #[test]
    fn recipe_serializes_small() {
        let def = recipe(4096.0);
        let ron = ron::ser::to_string(&def).unwrap();
        // The whole point: a world recipe is BYTES, not hundreds of MBs. It
        // used to also carry road strokes, which were the only thing in it
        // that grew with the world; without them the recipe is four numbers
        // and its size no longer depends on the map at all.
        assert!(ron.len() < 512, "recipe unexpectedly large: {}", ron.len());
        let back: GeneratedWorld = ron::de::from_str(&ron).unwrap();
        assert_eq!(back, def);
    }

    /// A recipe written before roads were removed still loads.
    ///
    /// Every shipped `map.ron` has a `strokes: []` field that no longer exists
    /// on the struct. Serde ignores unknown fields, so this passes -- but it
    /// passes by a default that a future `deny_unknown_fields` would silently
    /// take away, and the failure would be "the world will not load".
    #[test]
    fn a_recipe_with_the_old_strokes_field_still_loads() {
        let legacy = r#"(
            style: Showcase,
            seed: 91,
            generator_version: 5,
            half_extent: 4096.0,
            strokes: [],
        )"#;
        let parsed: GeneratedWorld =
            ron::de::from_str(legacy).expect("legacy recipe with strokes must still parse");
        assert_eq!(parsed.seed, 91);
        assert_eq!(parsed.half_extent, 4096.0);
    }
}

#[cfg(test)]
mod climate_tests {
    use super::*;

    #[test]
    fn climate_bands_behave() {
        let seed = 42;
        let half = 4096.0;
        // Map middle: temperate — no snow, no meaningful desert.
        let eq = climate_at(seed, 0.0, 0.0, 5.0, half);
        assert_eq!(eq.snow, 0.0);
        assert!(eq.dry < 0.1, "middle dry {}", eq.dry);
        // North pole (-z, top of the minimap): full snow and frost.
        let north = climate_at(seed, 0.0, -4000.0, 5.0, half);
        assert!(north.snow > 0.95, "north snow {}", north.snow);
        assert!(north.frost > 0.95);
        assert_eq!(north.dry, 0.0);
        // South pole (+z): full desert, never snow.
        let south = climate_at(seed, 0.0, 4000.0, 5.0, half);
        assert!(south.dry > 0.95, "south dry {}", south.dry);
        assert_eq!(south.snow, 0.0);
        // Mid-north temperate: neither snow nor desert.
        let mid = climate_at(seed, 0.0, -1600.0, 5.0, half);
        assert_eq!(mid.snow, 0.0);
        assert!(mid.dry < 0.05);
        // Altitude cools: a 60m peak at mid-north latitude frosts sooner...
        let peak = climate_at(seed, 0.0, -1600.0, 60.0, half);
        assert!(peak.frost > mid.frost);
        // ...and pushes the desert back off southern high ground.
        let desert_edge = climate_at(seed, 0.0, 2600.0, 5.0, half);
        let desert_peak = climate_at(seed, 0.0, 2600.0, 60.0, half);
        assert!(desert_peak.dry < desert_edge.dry);
        // Band edges wobble along x: sample the frost band at several
        // meridians and require a real spread (a single pair can straddle a
        // wobble node and pass by float dust).
        let spread = [-3000.0_f32, -1500.0, 0.0, 1500.0, 3000.0]
            .iter()
            .map(|&x| climate_at(seed, x, -2540.0, 5.0, half).frost)
            .fold((f32::MAX, f32::MIN), |(lo, hi), v| (lo.min(v), hi.max(v)));
        assert!(spread.1 - spread.0 > 0.01, "frost line should wobble: {spread:?}");
    }
}
